/**
 * icons.ts — Icon Barrel File
 * ─────────────────────────────────────────────────────────────
 * Centraliza las exportaciones de lucide-react para mejorar el
 * Tree Shaking y tener control estricto de los íconos incluidos
 * en el bundle de la aplicación.
 */

import type { LucideIcon } from 'lucide-react';

export type { LucideIcon };

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Award,
  BarChart3,
  Bike,
  BrainCircuit,
  Calculator,
  Calendar,
  Car,
  Check,
  Flame,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Coins,
  CheckCircle,
  DollarSign,
  Filter,
  Fuel,
  History,
  Info,
  HelpCircle,
  Heart,
  LayoutDashboard,
  Lightbulb,
  Lock,
  Map,
  Minus,
  Navigation,
  NotebookPen,
  MapPin,
  Package,
  PartyPopper,
  Plus,
  Gauge,
  Pencil,
  RefreshCw,
  Rocket,
  RotateCcw,
  Settings,
  Receipt,
  Star,
  Target,
  TimerReset,
  TrafficCone,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  User,
  X,
  Zap,
  Wrench,
  ShieldCheck,
  Home,
  Timer,
  Save,
} from 'lucide-react';
